server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
spring:
  profiles: peer1

---

server:
  port: 8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8761/eureka/,http://peer3:8763/eureka/
spring:
  profiles: peer2

---

server:
  port: 8763
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
spring:
  profiles: peer3