# 前置条件
#1. 先通过maven插件将项目build在dockerhost
#2. 在dockerhost中能通过docker images能查询到了下文中的各个image
#3. 将文件该文件内容copy到dockerhost中的任意目录的docker-compose.yaml文件中, 再执行docker-compose up, 将按照下文的配置启动相应容器

version: '2'
networks:
  vdp-network:
    driver: bridge
services:
  eurekaserver1:
    image: 183.63.187.150:8082/itmuch/microservice-discovery-eureka-ha:0.0.5
    networks:
      - vdp-network
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=peer1
    hostname: eurekaserver1

  eurekaserver2:
    image: 183.63.187.150:8082/itmuch/microservice-discovery-eureka-ha:0.0.5
    networks:
      - vdp-network
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=peer2
    hostname: eurekaserver2

  eurekaserver3:
    image: 183.63.187.150:8082/itmuch/microservice-discovery-eureka-ha:0.0.5
    networks:
      - vdp-network
    ports:
      - "8763:8763"
    environment:
      - spring.profiles.active=peer3
    hostname: eurekaserver3
