# monitor: spring-boot-starter-actuator config and Spring Boot Admin Server config
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: ["*"]  # monitor all  # ["health", "info"]
eureka:
  client:
    serviceUrl:
#      defaultZone: http://admin:123@localhost:10000/eureka/
#      defaultZone: http://localhost:10000/eureka/
      defaultZone: http://eurekaserver1:8761/eureka/,http://eurekaserver2:8761/eureka/,http://eurekaserver3:8761/eureka/
#      defaultZone: http://${security.user.name}:${security.user.password}@localhost:10000/eureka/
    healthcheck: # dependency on spring-boot-starter-actuator
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  mail:
    #smtp.qq.com,smtp.163.com
    host: smtp.163.com
#    username: 593213437
#    password: lhp,93a5f22,lxn
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  boot:
    admin:
      notify:
        mail:
#          from: 593213437@qq.com
          to: longxiaonan@163.com
